[package]
name = "rooms"
description = "Rust Operations On Mathematical Objects."
version = "0.1.0-alpha"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/Ediblelnk/rooms"

[dependencies]
